
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/NuzzleDB
    username: root
    password: 'Jny617^^*'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  
#  CREATE DATABASE NuzzleDB;
#
#  USE NuzzleDB;
#
#-- Table: PET
#  CREATE TABLE pet (
#  pet_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  pet_type VARCHAR(255),
#  pet_img VARCHAR(255)
#  );
#
#-- Table: FAMILY
#  CREATE TABLE family (
#  family_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  pet_id BIGINT,
#  pet_color VARCHAR(255),
#  pet_name VARCHAR(255),
#  family_status VARCHAR(255),
#  invitation_code VARCHAR(255),
#  FOREIGN KEY (pet_id) REFERENCES pet(pet_id)
#  );
#
#-- Table: KEYWORD
#  CREATE TABLE keyword (
#  keyword_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  keyword VARCHAR(255)
#  );
#
#-- Table: USER
#  CREATE TABLE user (
#  user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  family_id BIGINT,
#  user_name VARCHAR(255),
#  gender VARCHAR(255),
#  serial_id VARCHAR(255) UNIQUE,
#  password VARCHAR(255),
#  role VARCHAR(255),
#  birth_date DATETIME(6),
#  FOREIGN KEY (family_id) REFERENCES family(family_id)
#  );
#
#-- Table: Question
#  CREATE TABLE question (
#  question_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  question_contents VARCHAR(255)
#  );
#
#-- Table: Picture
#  CREATE TABLE picture (
#  picture_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  user_id BIGINT,
#  picture_url VARCHAR(255),
#  upload_date TIMESTAMP,
#  FOREIGN KEY (user_id) REFERENCES user(user_id)
#  );
#
#-- Table: Emoji
#  CREATE TABLE emoji (
#  emoji_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  emoji_img VARCHAR(255)
#  );
#
#-- Table: Alarm
#  CREATE TABLE alarm (
#  alarm_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  contents VARCHAR(255),
#  alarm_status BOOLEAN
#  );
#
#-- Table: UserAlarm
#  CREATE TABLE user_alarm (
#  user_alarm_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  user_id BIGINT,
#  alarm_id BIGINT,
#  alarm_time TIMESTAMP,
#  FOREIGN KEY (user_id) REFERENCES user(user_id),
#  FOREIGN KEY (alarm_id) REFERENCES alarm(alarm_id)
#  );
#
#-- Table: FamilyQuestion
#  CREATE TABLE family_question (
#  family_id BIGINT,
#  question_id BIGINT,
#  PRIMARY KEY (family_id, question_id),
#  FOREIGN KEY (family_id) REFERENCES family(family_id),
#  FOREIGN KEY (question_id) REFERENCES question(question_id)
#  );
#
#-- Table: FAMILYKEYWORD
#  CREATE TABLE family_keyword (
#  family_keyword_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  keyword_id BIGINT,
#  family_id BIGINT,
#  FOREIGN KEY (family_id) REFERENCES family(family_id),
#  FOREIGN KEY (keyword_id) REFERENCES keyword(keyword_id)
#  );
#
#-- Table: PictureEmoji
#  CREATE TABLE picture_emoji (
#  picture_emoji_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  picture_id BIGINT,
#  emoji_id BIGINT,
#  FOREIGN KEY (picture_id) REFERENCES picture(picture_id),
#  FOREIGN KEY (emoji_id) REFERENCES emoji(emoji_id)
#  );
#
#-- Table: Answer
#  CREATE TABLE answer (
#  answer_id BIGINT PRIMARY KEY AUTO_INCREMENT,
#  question_id BIGINT,
#  family_id BIGINT,
#  user_id BIGINT,
#  answer_contents VARCHAR(255),
#  answer_date TIMESTAMP,
#  answer_status BOOLEAN,
#  FOREIGN KEY (question_id) REFERENCES family_question(question_id),
#  FOREIGN KEY (family_id) REFERENCES family_question(family_id),
#  FOREIGN KEY (user_id) REFERENCES user(user_id)
#  );
#
#  #  ---------------------- 더미데이터 부분------------------------
#  -- Inserting data into PET table
#  INSERT INTO pet (pet_type, pet_img) VALUES
#  ('Dog', 'dog1.jpg'),
#  ('Cat', 'cat1.jpg'),
#  ('Bird', 'bird1.jpg');
#
#  -- Inserting data into FAMILY table
#  INSERT INTO family (pet_id, pet_color, pet_name, family_status, invitation_code) VALUES
#  (1, 'Color1', 'Buddy', 'Active', 'abcd-1234-efgh-5678'),
#  (2, 'Color2', 'Whiskers', 'Active', 'ijkl-9101-mnop-1121'),
#  (3, 'Color3', 'Tweety', 'Active', 'qrst-3141-uvwx-5161');
#
#  -- Inserting data into KEYWORD table
#  INSERT INTO keyword (keyword) VALUES
#  ('Playful'),
#  ('Lazy'),
#  ('Noisy');
#
#  -- Inserting data into USER table
#  INSERT INTO user (family_id, user_name, gender, serial_id, password, role, birth_date) VALUES
#  (1, 'Alice', 'Female', 'U001', 'pass123', 'Admin', '1990-01-01 00:00:00'),
#  (2, 'Bob', 'Male', 'U002', 'pass456', 'User', '1985-05-15 00:00:00'),
#  (3, 'Charlie', 'Male', 'U003', 'pass789', 'User', '2000-07-20 00:00:00');
#
#  -- Inserting data into Question table
#  INSERT INTO question (question_contents) VALUES
#  ('What is your pet\'s favorite activity?'),
#  ('How often do you take your pet to the vet?'),
#  ('What do you feed your pet?');
#
#  -- Inserting data into Picture table
#  INSERT INTO picture (user_id, picture_url, upload_date) VALUES
#  (1, 'pic1.jpg', '2024-01-01 00:00:00'),
#  (2, 'pic2.jpg', '2024-02-01 00:00:00'),
#  (3, 'pic3.jpg', '2024-03-01 00:00:00');
#
#  -- Inserting data into Emoji table
#  INSERT INTO emoji (emoji_img) VALUES
#  ('smile.png'),
#  ('sad.png'),
#  ('heart.png');
#
#  -- Inserting data into Alarm table
#  INSERT INTO alarm (contents, alarm_status) VALUES
#  ('Time to feed your pet', TRUE),
#  ('Vet appointment tomorrow', FALSE),
#  ('Pet grooming day', TRUE);
#
#  -- Inserting data into UserAlarm table
#  INSERT INTO user_alarm (user_id, alarm_id, alarm_time) VALUES
#  (1, 1, '2024-01-01 08:00:00'),
#  (2, 2, '2024-02-01 10:00:00'),
#  (3, 3, '2024-03-01 09:00:00');
#
#  -- Inserting data into FamilyQuestion table
#  INSERT INTO family_question (family_id, question_id) VALUES
#  (1, 1),
#  (2, 2),
#  (3, 3);
#
#  -- Inserting data into FAMILYKEYWORD table
#  INSERT INTO family_keyword (keyword_id, family_id) VALUES
#  (1, 1),
#  (2, 2),
#  (3, 3);
#
#  -- Inserting data into PictureEmoji table
#  INSERT INTO picture_emoji (picture_id, emoji_id) VALUES
#  (1, 1),
#  (2, 2),
#  (3, 3);
#
#  -- Inserting data into Answer table
#  INSERT INTO answer (question_id, family_id, user_id, answer_contents, answer_date, answer_status) VALUES
#  (1, 1, 1, 'Playing fetch', '2024-01-02 00:00:00', TRUE),
#  (2, 2, 2, 'Twice a year', '2024-02-02 00:00:00', TRUE),
#  (3, 3, 3, 'Seeds and fruits', '2024-03-02 00:00:00', TRUE);